// This file is auto-generated by @hey-api/openapi-ts

export type CreateAccountBalanceDto = {
  date: string;
  amount: number;
  subject: string;
};

export enum FinancialTransactionType {
  ACCOUNT_BALANCE = 'ACCOUNT_BALANCE',
  GROCERY = 'GROCERY',
  USER_BALANCE = 'USER_BALANCE',
}

export type AccountBalance = {
  financialTransactionType: FinancialTransactionType;
  subject: string;
  date: string;
  amount: number;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type UpdateAccountBalanceDto = {
  date?: string;
  amount?: number;
  subject?: string;
};

export type AccountBalanceDto = {
  accountBalance: number;
};

export type Grocery = {
  financialTransactionType: FinancialTransactionType;
  users?: Array<User>;
  billingPeriod?: BillingPeriod | null;
  date: string;
  amount: number;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type BillingPeriod = {
  billingDate: string;
  salads?: Array<Salad>;
  saladPrice: number;
  groceries?: Array<Grocery>;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type Salad = {
  date: string;
  user: User;
  billingPeriod: BillingPeriod | null;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type UserBalance = {
  financialTransactionType: FinancialTransactionType;
  user?: User;
  date: string;
  amount: number;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type User = {
  email: string;
  displayName: string;
  active: boolean;
  salads?: Array<Salad>;
  userBalances?: Array<UserBalance>;
  groceries?: Array<Grocery>;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type UserAccountBalanceDto = {
  user: User;
  balance: number;
};

export type CurrentBillingPeriodDto = {
  saladPrice?: number;
  salads: Array<Salad>;
  groceries: Array<Grocery>;
};

export type CloseCurrentBillingPeriodDto = {
  until: string;
  countedAccountBalance: number;
};

export type CreateGroceryDto = {
  date: string;
  amount: number;
  userIds: Array<string>;
};

export type UpdateGroceryDto = {
  date?: string;
  amount?: number;
  userIds?: Array<string>;
};

export type CreateSaladDto = {
  date: string;
  userId: string;
};

export type UpdateSaladDto = {
  date?: string;
  userId?: string;
};

export type CreateUserBalanceDto = {
  date: string;
  amount: number;
  userId: string;
};

export type UpdateUserBalanceDto = {
  date?: string;
  amount?: number;
  userId?: string;
};

export type CreateUserDto = {
  email: string;
  displayName: string;
};

export type UpdateUserDto = {
  active?: boolean;
  displayName?: string;
};

export type $OpenApiTs = {
  '/api/v1/health': {
    get: {
      res: {
        /**
         * The Health Check is successful
         */
        200: {
          status?: string;
          info?: Record<
            string,
            {
              status: string;
              [key: string]: unknown;
            }
          > | null;
          error?: Record<
            string,
            {
              status: string;
              [key: string]: unknown;
            }
          > | null;
          details?: Record<
            string,
            {
              status: string;
              [key: string]: unknown;
            }
          >;
        };
      };
    };
  };
  '/api/v1/account-balances': {
    post: {
      req: {
        requestBody: CreateAccountBalanceDto;
      };
      res: {
        201: AccountBalance;
      };
    };
    get: {
      res: {
        200: Array<AccountBalance>;
      };
    };
  };
  '/api/v1/account-balances/{id}': {
    get: {
      req: {
        id: string;
      };
      res: {
        200: AccountBalance;
      };
    };
    patch: {
      req: {
        id: string;
        requestBody: UpdateAccountBalanceDto;
      };
      res: {
        200: AccountBalance;
      };
    };
    delete: {
      req: {
        id: string;
      };
      res: {
        200: AccountBalance;
      };
    };
  };
  '/api/v1/balances/account': {
    get: {
      res: {
        200: AccountBalanceDto;
      };
    };
  };
  '/api/v1/balances/users': {
    get: {
      req: {
        active?: boolean;
      };
      res: {
        200: Array<UserAccountBalanceDto>;
      };
    };
  };
  '/api/v1/balances/users/{userId}': {
    get: {
      req: {
        userId: string;
      };
      res: {
        200: UserAccountBalanceDto;
      };
    };
  };
  '/api/v1/billing-periods': {
    get: {
      res: {
        200: Array<BillingPeriod>;
      };
    };
  };
  '/api/v1/billing-periods/{id}': {
    get: {
      req: {
        id: string;
      };
      res: {
        200: BillingPeriod;
      };
    };
  };
  '/api/v1/current-billing-period': {
    get: {
      req: {
        until?: string;
      };
      res: {
        200: CurrentBillingPeriodDto;
      };
    };
    post: {
      req: {
        requestBody: CloseCurrentBillingPeriodDto;
      };
      res: {
        201: BillingPeriod;
      };
    };
  };
  '/api/v1/financial-transactions': {
    get: {
      res: {
        200: Array<AccountBalance | UserBalance | Grocery>;
      };
    };
  };
  '/api/v1/groceries': {
    post: {
      req: {
        requestBody: CreateGroceryDto;
      };
      res: {
        201: Grocery;
      };
    };
    get: {
      res: {
        200: Array<Grocery>;
      };
    };
  };
  '/api/v1/groceries/{id}': {
    get: {
      req: {
        id: string;
      };
      res: {
        200: Grocery;
      };
    };
    patch: {
      req: {
        id: string;
        requestBody: UpdateGroceryDto;
      };
      res: {
        200: Grocery;
      };
    };
    delete: {
      req: {
        id: string;
      };
      res: {
        200: Grocery;
      };
    };
  };
  '/api/v1/salads': {
    post: {
      req: {
        requestBody: CreateSaladDto;
      };
      res: {
        201: Salad;
      };
    };
    get: {
      res: {
        200: Array<Salad>;
      };
    };
  };
  '/api/v1/salads/{id}': {
    get: {
      req: {
        id: string;
      };
      res: {
        200: Salad;
      };
    };
    patch: {
      req: {
        id: string;
        requestBody: UpdateSaladDto;
      };
      res: {
        200: Salad;
      };
    };
    delete: {
      req: {
        id: string;
      };
      res: {
        200: Salad;
      };
    };
  };
  '/api/v1/user-balances': {
    post: {
      req: {
        requestBody: CreateUserBalanceDto;
      };
      res: {
        201: UserBalance;
      };
    };
    get: {
      res: {
        200: Array<UserBalance>;
      };
    };
  };
  '/api/v1/user-balances/{id}': {
    get: {
      req: {
        id: string;
      };
      res: {
        200: UserBalance;
      };
    };
    patch: {
      req: {
        id: string;
        requestBody: UpdateUserBalanceDto;
      };
      res: {
        200: UserBalance;
      };
    };
    delete: {
      req: {
        id: string;
      };
      res: {
        200: UserBalance;
      };
    };
  };
  '/api/v1/users': {
    post: {
      req: {
        requestBody: CreateUserDto;
      };
      res: {
        201: User;
      };
    };
    get: {
      req: {
        active?: boolean;
      };
      res: {
        200: Array<User>;
      };
    };
  };
  '/api/v1/users/{id}': {
    get: {
      req: {
        id: string;
        includeSalads?: boolean;
        includesUserBalances?: boolean;
      };
      res: {
        200: User;
      };
    };
    patch: {
      req: {
        id: string;
        requestBody: UpdateUserDto;
      };
      res: {
        200: User;
      };
    };
    delete: {
      req: {
        id: string;
      };
      res: {
        200: User;
      };
    };
  };
};
