// This file is auto-generated by @hey-api/openapi-ts

export const $CreateAccountBalanceDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    amount: {
      type: "number",
    },
    subject: {
      type: "string",
    },
  },
  required: ["date", "amount", "subject"],
} as const;

export const $FinancialTransactionType = {
  type: "string",
  enum: ["ACCOUNT_BALANCE", "GROCERY", "USER_BALANCE"],
} as const;

export const $AccountBalance = {
  type: "object",
  properties: {
    financialTransactionType: {
      $ref: "#/components/schemas/FinancialTransactionType",
    },
    subject: {
      type: "string",
    },
    date: {
      type: "string",
    },
    amount: {
      type: "number",
    },
    id: {
      type: "string",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "financialTransactionType",
    "subject",
    "date",
    "amount",
    "id",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $UpdateAccountBalanceDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    amount: {
      type: "number",
    },
    subject: {
      type: "string",
    },
  },
} as const;

export const $AccountBalanceDto = {
  type: "object",
  properties: {
    accountBalance: {
      type: "number",
    },
  },
  required: ["accountBalance"],
} as const;

export const $Grocery = {
  type: "object",
  properties: {
    financialTransactionType: {
      $ref: "#/components/schemas/FinancialTransactionType",
    },
    users: {
      type: "array",
      items: {
        $ref: "#/components/schemas/User",
      },
    },
    billingPeriod: {
      nullable: true,
      allOf: [
        {
          $ref: "#/components/schemas/BillingPeriod",
        },
      ],
    },
    date: {
      type: "string",
    },
    amount: {
      type: "number",
    },
    id: {
      type: "string",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["financialTransactionType", "date", "amount", "id", "createdAt", "updatedAt"],
} as const;

export const $BillingPeriod = {
  type: "object",
  properties: {
    billingDate: {
      type: "string",
    },
    salads: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Salad",
      },
    },
    saladPrice: {
      type: "number",
    },
    groceries: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Grocery",
      },
    },
    id: {
      type: "string",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["billingDate", "saladPrice", "id", "createdAt", "updatedAt"],
} as const;

export const $Salad = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    user: {
      $ref: "#/components/schemas/User",
    },
    billingPeriod: {
      nullable: true,
      allOf: [
        {
          $ref: "#/components/schemas/BillingPeriod",
        },
      ],
    },
    id: {
      type: "string",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["date", "user", "billingPeriod", "id", "createdAt", "updatedAt"],
} as const;

export const $UserBalance = {
  type: "object",
  properties: {
    financialTransactionType: {
      $ref: "#/components/schemas/FinancialTransactionType",
    },
    user: {
      $ref: "#/components/schemas/User",
    },
    date: {
      type: "string",
    },
    amount: {
      type: "number",
    },
    id: {
      type: "string",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["financialTransactionType", "date", "amount", "id", "createdAt", "updatedAt"],
} as const;

export const $User = {
  type: "object",
  properties: {
    email: {
      type: "string",
    },
    displayName: {
      type: "string",
    },
    active: {
      type: "boolean",
    },
    salads: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Salad",
      },
    },
    userBalances: {
      type: "array",
      items: {
        $ref: "#/components/schemas/UserBalance",
      },
    },
    groceries: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Grocery",
      },
    },
    id: {
      type: "string",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["email", "displayName", "active", "id", "createdAt", "updatedAt"],
} as const;

export const $UserAccountBalanceDto = {
  type: "object",
  properties: {
    user: {
      $ref: "#/components/schemas/User",
    },
    balance: {
      type: "number",
    },
  },
  required: ["user", "balance"],
} as const;

export const $CurrentBillingPeriodDto = {
  type: "object",
  properties: {
    saladPrice: {
      type: "number",
    },
    salads: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Salad",
      },
    },
    groceries: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Grocery",
      },
    },
  },
  required: ["salads", "groceries"],
} as const;

export const $CloseCurrentBillingPeriodDto = {
  type: "object",
  properties: {
    until: {
      type: "string",
    },
    countedAccountBalance: {
      type: "number",
      minimum: 0,
    },
  },
  required: ["until", "countedAccountBalance"],
} as const;

export const $CreateGroceryDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    amount: {
      type: "number",
      maximum: -1,
    },
    userIds: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: ["date", "amount", "userIds"],
} as const;

export const $UpdateGroceryDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    amount: {
      type: "number",
      maximum: -1,
    },
    userIds: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const $CreateSaladDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    userId: {
      type: "string",
    },
  },
  required: ["date", "userId"],
} as const;

export const $UpdateSaladDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    userId: {
      type: "string",
    },
  },
} as const;

export const $CreateUserBalanceDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    amount: {
      type: "number",
    },
    userId: {
      type: "string",
    },
  },
  required: ["date", "amount", "userId"],
} as const;

export const $UpdateUserBalanceDto = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    amount: {
      type: "number",
    },
    userId: {
      type: "string",
    },
  },
} as const;

export const $CreateUserDto = {
  type: "object",
  properties: {
    email: {
      type: "string",
    },
    displayName: {
      type: "string",
    },
  },
  required: ["email", "displayName"],
} as const;

export const $UpdateUserDto = {
  type: "object",
  properties: {
    active: {
      type: "boolean",
    },
    displayName: {
      type: "string",
    },
  },
} as const;
