// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type { $OpenApiTs } from "./models";

export class HealthService {
  /**
   * @returns any The Health Check is successful
   * @throws ApiError
   */
  public static check(): CancelablePromise<$OpenApiTs["/api/v1/health"]["get"]["res"][200]> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/health",
      errors: {
        503: `The Health Check is not successful`,
      },
    });
  }
}

export class AccountBalancesService {
  /**
   * @returns AccountBalance
   * @throws ApiError
   */
  public static create(
    data: $OpenApiTs["/api/v1/account-balances"]["post"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/account-balances"]["post"]["res"][201]> {
    const { requestBody } = data;
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/account-balances",
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns AccountBalance
   * @throws ApiError
   */
  public static findAll(): CancelablePromise<
    $OpenApiTs["/api/v1/account-balances"]["get"]["res"][200]
  > {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/account-balances",
    });
  }

  /**
   * @returns AccountBalance
   * @throws ApiError
   */
  public static findOne(
    data: $OpenApiTs["/api/v1/account-balances/{id}"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/account-balances/{id}"]["get"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/account-balances/{id}",
      path: {
        id,
      },
    });
  }

  /**
   * @returns AccountBalance
   * @throws ApiError
   */
  public static update(
    data: $OpenApiTs["/api/v1/account-balances/{id}"]["patch"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/account-balances/{id}"]["patch"]["res"][200]> {
    const { id, requestBody } = data;
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/account-balances/{id}",
      path: {
        id,
      },
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns AccountBalance
   * @throws ApiError
   */
  public static remove(
    data: $OpenApiTs["/api/v1/account-balances/{id}"]["delete"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/account-balances/{id}"]["delete"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/account-balances/{id}",
      path: {
        id,
      },
    });
  }
}

export class BalancesService {
  /**
   * @returns AccountBalanceDto
   * @throws ApiError
   */
  public static getAccount(): CancelablePromise<
    $OpenApiTs["/api/v1/balances/account"]["get"]["res"][200]
  > {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/balances/account",
    });
  }

  /**
   * @returns UserAccountBalanceDto
   * @throws ApiError
   */
  public static getUsers(
    data: $OpenApiTs["/api/v1/balances/users"]["get"]["req"] = {},
  ): CancelablePromise<$OpenApiTs["/api/v1/balances/users"]["get"]["res"][200]> {
    const { active } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/balances/users",
      query: {
        active,
      },
    });
  }

  /**
   * @returns UserAccountBalanceDto
   * @throws ApiError
   */
  public static getUser(
    data: $OpenApiTs["/api/v1/balances/users/{userId}"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/balances/users/{userId}"]["get"]["res"][200]> {
    const { userId } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/balances/users/{userId}",
      path: {
        userId,
      },
    });
  }
}

export class BillingPeriodsService {
  /**
   * @returns BillingPeriod
   * @throws ApiError
   */
  public static findAll(): CancelablePromise<
    $OpenApiTs["/api/v1/billing-periods"]["get"]["res"][200]
  > {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/billing-periods",
    });
  }

  /**
   * @returns BillingPeriod
   * @throws ApiError
   */
  public static findOne(
    data: $OpenApiTs["/api/v1/billing-periods/{id}"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/billing-periods/{id}"]["get"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/billing-periods/{id}",
      path: {
        id,
      },
    });
  }
}

export class CurrentBillingPeriodService {
  /**
   * @returns CurrentBillingPeriodDto
   * @throws ApiError
   */
  public static get(
    data: $OpenApiTs["/api/v1/current-billing-period"]["get"]["req"] = {},
  ): CancelablePromise<$OpenApiTs["/api/v1/current-billing-period"]["get"]["res"][200]> {
    const { until } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/current-billing-period",
      query: {
        until,
      },
    });
  }

  /**
   * @returns BillingPeriod
   * @throws ApiError
   */
  public static close(
    data: $OpenApiTs["/api/v1/current-billing-period"]["post"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/current-billing-period"]["post"]["res"][201]> {
    const { requestBody } = data;
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/current-billing-period",
      body: requestBody,
      mediaType: "application/json",
    });
  }
}

export class FinancialTransactionsService {
  /**
   * @returns unknown
   * @throws ApiError
   */
  public static get(): CancelablePromise<
    $OpenApiTs["/api/v1/financial-transactions"]["get"]["res"][200]
  > {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/financial-transactions",
    });
  }
}

export class GroceriesService {
  /**
   * @returns Grocery
   * @throws ApiError
   */
  public static create(
    data: $OpenApiTs["/api/v1/groceries"]["post"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/groceries"]["post"]["res"][201]> {
    const { requestBody } = data;
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/groceries",
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns Grocery
   * @throws ApiError
   */
  public static findAll(): CancelablePromise<$OpenApiTs["/api/v1/groceries"]["get"]["res"][200]> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/groceries",
    });
  }

  /**
   * @returns Grocery
   * @throws ApiError
   */
  public static findOne(
    data: $OpenApiTs["/api/v1/groceries/{id}"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/groceries/{id}"]["get"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/groceries/{id}",
      path: {
        id,
      },
    });
  }

  /**
   * @returns Grocery
   * @throws ApiError
   */
  public static update(
    data: $OpenApiTs["/api/v1/groceries/{id}"]["patch"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/groceries/{id}"]["patch"]["res"][200]> {
    const { id, requestBody } = data;
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/groceries/{id}",
      path: {
        id,
      },
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns Grocery
   * @throws ApiError
   */
  public static remove(
    data: $OpenApiTs["/api/v1/groceries/{id}"]["delete"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/groceries/{id}"]["delete"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/groceries/{id}",
      path: {
        id,
      },
    });
  }
}

export class SaladsService {
  /**
   * @returns Salad
   * @throws ApiError
   */
  public static create(
    data: $OpenApiTs["/api/v1/salads"]["post"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/salads"]["post"]["res"][201]> {
    const { requestBody } = data;
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/salads",
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns Salad
   * @throws ApiError
   */
  public static findAll(): CancelablePromise<$OpenApiTs["/api/v1/salads"]["get"]["res"][200]> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/salads",
    });
  }

  /**
   * @returns Salad
   * @throws ApiError
   */
  public static findOne(
    data: $OpenApiTs["/api/v1/salads/{id}"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/salads/{id}"]["get"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/salads/{id}",
      path: {
        id,
      },
    });
  }

  /**
   * @returns Salad
   * @throws ApiError
   */
  public static update(
    data: $OpenApiTs["/api/v1/salads/{id}"]["patch"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/salads/{id}"]["patch"]["res"][200]> {
    const { id, requestBody } = data;
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/salads/{id}",
      path: {
        id,
      },
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns Salad
   * @throws ApiError
   */
  public static remove(
    data: $OpenApiTs["/api/v1/salads/{id}"]["delete"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/salads/{id}"]["delete"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/salads/{id}",
      path: {
        id,
      },
    });
  }
}

export class UserBalancesService {
  /**
   * @returns UserBalance
   * @throws ApiError
   */
  public static create(
    data: $OpenApiTs["/api/v1/user-balances"]["post"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/user-balances"]["post"]["res"][201]> {
    const { requestBody } = data;
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/user-balances",
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns UserBalance
   * @throws ApiError
   */
  public static findAll(): CancelablePromise<
    $OpenApiTs["/api/v1/user-balances"]["get"]["res"][200]
  > {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/user-balances",
    });
  }

  /**
   * @returns UserBalance
   * @throws ApiError
   */
  public static findOne(
    data: $OpenApiTs["/api/v1/user-balances/{id}"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/user-balances/{id}"]["get"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/user-balances/{id}",
      path: {
        id,
      },
    });
  }

  /**
   * @returns UserBalance
   * @throws ApiError
   */
  public static update(
    data: $OpenApiTs["/api/v1/user-balances/{id}"]["patch"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/user-balances/{id}"]["patch"]["res"][200]> {
    const { id, requestBody } = data;
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/user-balances/{id}",
      path: {
        id,
      },
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns UserBalance
   * @throws ApiError
   */
  public static remove(
    data: $OpenApiTs["/api/v1/user-balances/{id}"]["delete"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/user-balances/{id}"]["delete"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/user-balances/{id}",
      path: {
        id,
      },
    });
  }
}

export class UsersService {
  /**
   * @returns User
   * @throws ApiError
   */
  public static create(
    data: $OpenApiTs["/api/v1/users"]["post"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/users"]["post"]["res"][201]> {
    const { requestBody } = data;
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users",
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns User
   * @throws ApiError
   */
  public static findAll(
    data: $OpenApiTs["/api/v1/users"]["get"]["req"] = {},
  ): CancelablePromise<$OpenApiTs["/api/v1/users"]["get"]["res"][200]> {
    const { active } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users",
      query: {
        active,
      },
    });
  }

  /**
   * @returns User
   * @throws ApiError
   */
  public static findOne(
    data: $OpenApiTs["/api/v1/users/{id}"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/users/{id}"]["get"]["res"][200]> {
    const { id, includeSalads, includesUserBalances } = data;
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{id}",
      path: {
        id,
      },
      query: {
        includeSalads,
        includesUserBalances,
      },
    });
  }

  /**
   * @returns User
   * @throws ApiError
   */
  public static update(
    data: $OpenApiTs["/api/v1/users/{id}"]["patch"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/users/{id}"]["patch"]["res"][200]> {
    const { id, requestBody } = data;
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{id}",
      path: {
        id,
      },
      body: requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @returns User
   * @throws ApiError
   */
  public static remove(
    data: $OpenApiTs["/api/v1/users/{id}"]["delete"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/v1/users/{id}"]["delete"]["res"][200]> {
    const { id } = data;
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{id}",
      path: {
        id,
      },
    });
  }
}
