/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

import { Route as rootRouteImport } from './routes/__root';

const KassenstandLazyRouteImport = createFileRoute('/kassenstand')();
const IndexLazyRouteImport = createFileRoute('/')();
const SchwesternIndexLazyRouteImport = createFileRoute('/schwestern/')();
const AbrechnungsperiodenIndexLazyRouteImport = createFileRoute(
  '/abrechnungsperioden/',
)();
const AbrechnungsperiodeIndexLazyRouteImport = createFileRoute(
  '/abrechnungsperiode/',
)();
const SchwesternHinzufuegenLazyRouteImport = createFileRoute(
  '/schwestern/hinzufuegen',
)();
const EinkaeufeHinzufuegenLazyRouteImport = createFileRoute(
  '/einkaeufe/hinzufuegen',
)();
const EinkaeufeGroceryIdLazyRouteImport = createFileRoute(
  '/einkaeufe/$groceryId',
)();
const AbrechnungsperiodenBillingPeriodIdLazyRouteImport = createFileRoute(
  '/abrechnungsperioden/$billingPeriodId',
)();
const AbrechnungsperiodeAbschliessenLazyRouteImport = createFileRoute(
  '/abrechnungsperiode/abschliessen',
)();
const SchwesternUserIdIndexLazyRouteImport = createFileRoute(
  '/schwestern/$userId/',
)();
const SchwesternUserIdBuchenLazyRouteImport = createFileRoute(
  '/schwestern/$userId/buchen',
)();

const KassenstandLazyRoute = KassenstandLazyRouteImport.update({
  id: '/kassenstand',
  path: '/kassenstand',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kassenstand.lazy').then((d) => d.Route));
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));
const SchwesternIndexLazyRoute = SchwesternIndexLazyRouteImport.update({
  id: '/schwestern/',
  path: '/schwestern/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/schwestern/index.lazy').then((d) => d.Route),
);
const AbrechnungsperiodenIndexLazyRoute =
  AbrechnungsperiodenIndexLazyRouteImport.update({
    id: '/abrechnungsperioden/',
    path: '/abrechnungsperioden/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/abrechnungsperioden/index.lazy').then((d) => d.Route),
  );
const AbrechnungsperiodeIndexLazyRoute =
  AbrechnungsperiodeIndexLazyRouteImport.update({
    id: '/abrechnungsperiode/',
    path: '/abrechnungsperiode/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/abrechnungsperiode/index.lazy').then((d) => d.Route),
  );
const SchwesternHinzufuegenLazyRoute =
  SchwesternHinzufuegenLazyRouteImport.update({
    id: '/schwestern/hinzufuegen',
    path: '/schwestern/hinzufuegen',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/schwestern/hinzufuegen.lazy').then((d) => d.Route),
  );
const EinkaeufeHinzufuegenLazyRoute =
  EinkaeufeHinzufuegenLazyRouteImport.update({
    id: '/einkaeufe/hinzufuegen',
    path: '/einkaeufe/hinzufuegen',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/einkaeufe/hinzufuegen.lazy').then((d) => d.Route),
  );
const EinkaeufeGroceryIdLazyRoute = EinkaeufeGroceryIdLazyRouteImport.update({
  id: '/einkaeufe/$groceryId',
  path: '/einkaeufe/$groceryId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/einkaeufe/$groceryId.lazy').then((d) => d.Route),
);
const AbrechnungsperiodenBillingPeriodIdLazyRoute =
  AbrechnungsperiodenBillingPeriodIdLazyRouteImport.update({
    id: '/abrechnungsperioden/$billingPeriodId',
    path: '/abrechnungsperioden/$billingPeriodId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/abrechnungsperioden/$billingPeriodId.lazy').then(
      (d) => d.Route,
    ),
  );
const AbrechnungsperiodeAbschliessenLazyRoute =
  AbrechnungsperiodeAbschliessenLazyRouteImport.update({
    id: '/abrechnungsperiode/abschliessen',
    path: '/abrechnungsperiode/abschliessen',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/abrechnungsperiode/abschliessen.lazy').then(
      (d) => d.Route,
    ),
  );
const SchwesternUserIdIndexLazyRoute =
  SchwesternUserIdIndexLazyRouteImport.update({
    id: '/schwestern/$userId/',
    path: '/schwestern/$userId/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/schwestern/$userId/index.lazy').then((d) => d.Route),
  );
const SchwesternUserIdBuchenLazyRoute =
  SchwesternUserIdBuchenLazyRouteImport.update({
    id: '/schwestern/$userId/buchen',
    path: '/schwestern/$userId/buchen',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/schwestern/$userId/buchen.lazy').then((d) => d.Route),
  );

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute;
  '/kassenstand': typeof KassenstandLazyRoute;
  '/abrechnungsperiode/abschliessen': typeof AbrechnungsperiodeAbschliessenLazyRoute;
  '/abrechnungsperioden/$billingPeriodId': typeof AbrechnungsperiodenBillingPeriodIdLazyRoute;
  '/einkaeufe/$groceryId': typeof EinkaeufeGroceryIdLazyRoute;
  '/einkaeufe/hinzufuegen': typeof EinkaeufeHinzufuegenLazyRoute;
  '/schwestern/hinzufuegen': typeof SchwesternHinzufuegenLazyRoute;
  '/abrechnungsperiode/': typeof AbrechnungsperiodeIndexLazyRoute;
  '/abrechnungsperioden/': typeof AbrechnungsperiodenIndexLazyRoute;
  '/schwestern/': typeof SchwesternIndexLazyRoute;
  '/schwestern/$userId/buchen': typeof SchwesternUserIdBuchenLazyRoute;
  '/schwestern/$userId/': typeof SchwesternUserIdIndexLazyRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute;
  '/kassenstand': typeof KassenstandLazyRoute;
  '/abrechnungsperiode/abschliessen': typeof AbrechnungsperiodeAbschliessenLazyRoute;
  '/abrechnungsperioden/$billingPeriodId': typeof AbrechnungsperiodenBillingPeriodIdLazyRoute;
  '/einkaeufe/$groceryId': typeof EinkaeufeGroceryIdLazyRoute;
  '/einkaeufe/hinzufuegen': typeof EinkaeufeHinzufuegenLazyRoute;
  '/schwestern/hinzufuegen': typeof SchwesternHinzufuegenLazyRoute;
  '/abrechnungsperiode': typeof AbrechnungsperiodeIndexLazyRoute;
  '/abrechnungsperioden': typeof AbrechnungsperiodenIndexLazyRoute;
  '/schwestern': typeof SchwesternIndexLazyRoute;
  '/schwestern/$userId/buchen': typeof SchwesternUserIdBuchenLazyRoute;
  '/schwestern/$userId': typeof SchwesternUserIdIndexLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexLazyRoute;
  '/kassenstand': typeof KassenstandLazyRoute;
  '/abrechnungsperiode/abschliessen': typeof AbrechnungsperiodeAbschliessenLazyRoute;
  '/abrechnungsperioden/$billingPeriodId': typeof AbrechnungsperiodenBillingPeriodIdLazyRoute;
  '/einkaeufe/$groceryId': typeof EinkaeufeGroceryIdLazyRoute;
  '/einkaeufe/hinzufuegen': typeof EinkaeufeHinzufuegenLazyRoute;
  '/schwestern/hinzufuegen': typeof SchwesternHinzufuegenLazyRoute;
  '/abrechnungsperiode/': typeof AbrechnungsperiodeIndexLazyRoute;
  '/abrechnungsperioden/': typeof AbrechnungsperiodenIndexLazyRoute;
  '/schwestern/': typeof SchwesternIndexLazyRoute;
  '/schwestern/$userId/buchen': typeof SchwesternUserIdBuchenLazyRoute;
  '/schwestern/$userId/': typeof SchwesternUserIdIndexLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/kassenstand'
    | '/abrechnungsperiode/abschliessen'
    | '/abrechnungsperioden/$billingPeriodId'
    | '/einkaeufe/$groceryId'
    | '/einkaeufe/hinzufuegen'
    | '/schwestern/hinzufuegen'
    | '/abrechnungsperiode/'
    | '/abrechnungsperioden/'
    | '/schwestern/'
    | '/schwestern/$userId/buchen'
    | '/schwestern/$userId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/kassenstand'
    | '/abrechnungsperiode/abschliessen'
    | '/abrechnungsperioden/$billingPeriodId'
    | '/einkaeufe/$groceryId'
    | '/einkaeufe/hinzufuegen'
    | '/schwestern/hinzufuegen'
    | '/abrechnungsperiode'
    | '/abrechnungsperioden'
    | '/schwestern'
    | '/schwestern/$userId/buchen'
    | '/schwestern/$userId';
  id:
    | '__root__'
    | '/'
    | '/kassenstand'
    | '/abrechnungsperiode/abschliessen'
    | '/abrechnungsperioden/$billingPeriodId'
    | '/einkaeufe/$groceryId'
    | '/einkaeufe/hinzufuegen'
    | '/schwestern/hinzufuegen'
    | '/abrechnungsperiode/'
    | '/abrechnungsperioden/'
    | '/schwestern/'
    | '/schwestern/$userId/buchen'
    | '/schwestern/$userId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  KassenstandLazyRoute: typeof KassenstandLazyRoute;
  AbrechnungsperiodeAbschliessenLazyRoute: typeof AbrechnungsperiodeAbschliessenLazyRoute;
  AbrechnungsperiodenBillingPeriodIdLazyRoute: typeof AbrechnungsperiodenBillingPeriodIdLazyRoute;
  EinkaeufeGroceryIdLazyRoute: typeof EinkaeufeGroceryIdLazyRoute;
  EinkaeufeHinzufuegenLazyRoute: typeof EinkaeufeHinzufuegenLazyRoute;
  SchwesternHinzufuegenLazyRoute: typeof SchwesternHinzufuegenLazyRoute;
  AbrechnungsperiodeIndexLazyRoute: typeof AbrechnungsperiodeIndexLazyRoute;
  AbrechnungsperiodenIndexLazyRoute: typeof AbrechnungsperiodenIndexLazyRoute;
  SchwesternIndexLazyRoute: typeof SchwesternIndexLazyRoute;
  SchwesternUserIdBuchenLazyRoute: typeof SchwesternUserIdBuchenLazyRoute;
  SchwesternUserIdIndexLazyRoute: typeof SchwesternUserIdIndexLazyRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kassenstand': {
      id: '/kassenstand';
      path: '/kassenstand';
      fullPath: '/kassenstand';
      preLoaderRoute: typeof KassenstandLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/schwestern/': {
      id: '/schwestern/';
      path: '/schwestern';
      fullPath: '/schwestern/';
      preLoaderRoute: typeof SchwesternIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/abrechnungsperioden/': {
      id: '/abrechnungsperioden/';
      path: '/abrechnungsperioden';
      fullPath: '/abrechnungsperioden/';
      preLoaderRoute: typeof AbrechnungsperiodenIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/abrechnungsperiode/': {
      id: '/abrechnungsperiode/';
      path: '/abrechnungsperiode';
      fullPath: '/abrechnungsperiode/';
      preLoaderRoute: typeof AbrechnungsperiodeIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/schwestern/hinzufuegen': {
      id: '/schwestern/hinzufuegen';
      path: '/schwestern/hinzufuegen';
      fullPath: '/schwestern/hinzufuegen';
      preLoaderRoute: typeof SchwesternHinzufuegenLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/einkaeufe/hinzufuegen': {
      id: '/einkaeufe/hinzufuegen';
      path: '/einkaeufe/hinzufuegen';
      fullPath: '/einkaeufe/hinzufuegen';
      preLoaderRoute: typeof EinkaeufeHinzufuegenLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/einkaeufe/$groceryId': {
      id: '/einkaeufe/$groceryId';
      path: '/einkaeufe/$groceryId';
      fullPath: '/einkaeufe/$groceryId';
      preLoaderRoute: typeof EinkaeufeGroceryIdLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/abrechnungsperioden/$billingPeriodId': {
      id: '/abrechnungsperioden/$billingPeriodId';
      path: '/abrechnungsperioden/$billingPeriodId';
      fullPath: '/abrechnungsperioden/$billingPeriodId';
      preLoaderRoute: typeof AbrechnungsperiodenBillingPeriodIdLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/abrechnungsperiode/abschliessen': {
      id: '/abrechnungsperiode/abschliessen';
      path: '/abrechnungsperiode/abschliessen';
      fullPath: '/abrechnungsperiode/abschliessen';
      preLoaderRoute: typeof AbrechnungsperiodeAbschliessenLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/schwestern/$userId/': {
      id: '/schwestern/$userId/';
      path: '/schwestern/$userId';
      fullPath: '/schwestern/$userId/';
      preLoaderRoute: typeof SchwesternUserIdIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/schwestern/$userId/buchen': {
      id: '/schwestern/$userId/buchen';
      path: '/schwestern/$userId/buchen';
      fullPath: '/schwestern/$userId/buchen';
      preLoaderRoute: typeof SchwesternUserIdBuchenLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  KassenstandLazyRoute: KassenstandLazyRoute,
  AbrechnungsperiodeAbschliessenLazyRoute:
    AbrechnungsperiodeAbschliessenLazyRoute,
  AbrechnungsperiodenBillingPeriodIdLazyRoute:
    AbrechnungsperiodenBillingPeriodIdLazyRoute,
  EinkaeufeGroceryIdLazyRoute: EinkaeufeGroceryIdLazyRoute,
  EinkaeufeHinzufuegenLazyRoute: EinkaeufeHinzufuegenLazyRoute,
  SchwesternHinzufuegenLazyRoute: SchwesternHinzufuegenLazyRoute,
  AbrechnungsperiodeIndexLazyRoute: AbrechnungsperiodeIndexLazyRoute,
  AbrechnungsperiodenIndexLazyRoute: AbrechnungsperiodenIndexLazyRoute,
  SchwesternIndexLazyRoute: SchwesternIndexLazyRoute,
  SchwesternUserIdBuchenLazyRoute: SchwesternUserIdBuchenLazyRoute,
  SchwesternUserIdIndexLazyRoute: SchwesternUserIdIndexLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
